version: '3.9'

services:
  backend:
    build: ./server
#    volumes:
#      - ./server:/go/src/app
    ports:
      - 4001:4001
      
  frontend:
    build: ./spa
#    volumes:
#      - ./spa:/app
    ports:
      - 5000:80
    environment:
      - VUE_APP_API_ENDPOINT=http://backend:4001/api
    depends_on: 
      - backend
  